CREATE DATABASE "Timely"
    WITH
    OWNER = postgres
    ENCODING = 'UTF8'
    LOCALE_PROVIDER = 'libc'
    CONNECTION LIMIT = -1

--
CREATE TABLE IF NOT EXISTS public.jobs
(
    id UUID NOT NULL PRIMARY KEY,
    slug CHARACTER VARYING(256) NOT NULL UNIQUE,
    description CHARACTER VARYING(1024),
    status CHARACTER VARYING(128) NOT NULL,
    reason CHARACTER VARYING(1024) NOT NULL,
    lastExecutionDate TIMESTAMP WITH TIME ZONE,
    nextExecutionDate TIMESTAMP WITH TIME ZONE
)

CREATE TABLE IF NOT EXISTS public.jobschedule
(
    id UUID NOT NULL PRIMARY KEY,
    jobId UUID NOT NULL REFERENCES jobs(id),
    frequency CHARACTER VARYING(256) NOT NULL
)