CREATE DATABASE "Timely"
    WITH
    OWNER = postgres
    ENCODING = 'UTF8'
    LOCALE_PROVIDER = 'libc'
    CONNECTION LIMIT = -1

--
CREATE TABLE IF NOT EXISTS job_schedule
(
    id UUID NOT NULL PRIMARY KEY,
    description CHARACTER VARYING(1024),
    frequency CHARACTER VARYING(256) NOT NULL,
    last_execution_date TIMESTAMP WITH TIME ZONE,
    next_execution_date TIMESTAMP WITH TIME ZONE
)

CREATE TABLE IF NOT EXISTS jobs
(
    id UUID NOT NULL PRIMARY KEY,
    schedule_id UUID NOT NULL REFERENCES job_schedule(id),
    slug CHARACTER VARYING(256) NOT NULL UNIQUE,
    status CHARACTER VARYING(128) NOT NULL,
    reason CHARACTER VARYING(1024)
)